mode:
  type: Standalone
  repository:
    type: JDBC

dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/db_tmp
    username: root
    password: xxx

    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 300000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 200
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 60000
      # 连接测试query
      connection-test-query: SELECT 1
rules:
- !SHARDING
    tables:
      t_user:
        actualDataNodes: ds0.t_user_$->{0..1}
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: t_user_inline
    shardingAlgorithms:
      t_user_inline:
        type: INLINE
        props:
          algorithm-expression: t_user_${id % 2}
- !SINGLE
  tables:
    # 加载指定数据源中的全部单表
    - ds0.*
  defaultDataSource: ds0 # 默认数据源，仅在执行 CREATE TABLE 创建单表时有效。缺失值为空，表示随机单播路由。
props:
  sql-show: false
